name: build-bbc-100-demo

on: [push]

jobs:
  build-demo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run crofter to build site source from CSV data & config
        run: crofter

      - name: Run quarto to build static site from source data
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: pages/content/mysite
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
